python main3.py -f 0
python main3.py -f 1
python main3.py -f 2
python main3.py -f 3
python main3.py -f 4
python main3.py -f 5
python main3.py -f 6
python main3.py -f 7
python main3.py -f 8
python main3.py -f 9
python main3.py -f 10